In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch  # essential that this is imported before calling functions returing tensor from cpp
from build import np_interop as cpp

In [3]:
dir(cpp)

['MDPTransition',
 'Policy',
 'ReplayBuffer',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'add',
 'get_arg_max',
 'minimal_tensor_create']

In [4]:
pol = cpp.Policy()
pol.train()

In [5]:
x = torch.randn(1,8)
print(x.shape)
res = pol.forward(x)
res

torch.Size([1, 8])


tensor([[0.3091, 0.1689, 0.2595, 0.2626]], grad_fn=<SoftmaxBackward0>)

In [6]:
torch.argmax(res)

tensor(0)

In [12]:
import gymnasium as gym

# Initialise the environment
# env = gym.make("LunarLander-v2", render_mode="human")
env = gym.make("LunarLander-v3", render_mode="human")

# Reset the environment to generate the first observation

observation, info = env.reset(seed=42)
num_sims: int = 10
total_returns: list = []

observation, info = env.reset(seed=42)
for i in range(num_sims):
    this_return = 0

    iteration: int = 0
    while True:
         
        # this is where you would insert your policy
        # action = env.action_space.sample()
        # action = pol.forward(torch.Tensor(observation)[None, :]).data
        action = torch.argmax(pol.forward(torch.Tensor(observation)[None, :])).item()

        # step (transition) through the environment with the action
        # receiving the next observation, reward and if the episode has terminated or truncated
        observation, reward, terminated, truncated, info = env.step(action)
        this_return += reward


        # If the episode has ended then we can reset to start a new episode
        if terminated or truncated:
            total_returns.append(torch.Tensor([this_return]))
            env.reset()
            break 


env.close()

2025-02-21 21:19:22.888 python[37165:9650152] +[IMKClient subclass]: chose IMKClient_Modern
2025-02-21 21:19:22.888 python[37165:9650152] +[IMKInputSession subclass]: chose IMKInputSession_Modern


In [22]:

total_returns_tens = torch.concatenate(total_returns)
total_returns_tens
total_returns_tens.sum() / total_returns_tens.shape[0]

tensor(-385.5892)

In [23]:
total_returns_tens

tensor([-432.9494, -287.4394, -376.2098, -231.0639, -318.2379, -459.1136,
        -461.0380, -366.0644, -438.4499, -485.3254])

: 

In [ ]:
import torch
ar = np.random.randint(10, size=10)
t = torch.from_numpy(ar)

In [ ]:
t[0].item()

In [3]:
import numpy as np

In [4]:
trans = cpp.MDPTransition(np.random.randn(10), 3, 3)

In [5]:
dir(trans)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'get']

In [6]:
tget = trans.get()

In [ ]:
type(tget[2])

float

In [8]:
rb = cpp.ReplayBuffer()

In [9]:
rb.append(trans)

In [12]:
rb.as_list()[0].get()

(array([ 0.44682149,  1.02251277, -1.17257248, -0.0877718 ,  0.83130534,
        -0.38277112, -1.77815504,  0.36389223, -0.05845574,  1.70910758]),
 3,
 3.0)

In [7]:
print([rb.as_list()[i].get() for i in range(len(rb.as_list()))])

MemoryError: std::bad_alloc

In [20]:
import numpy as np
import torch
from build import np_interop as cpp

rb = cpp.ReplayBuffer()

for _ in range(3):
    rb.append(cpp.MDPTransition(np.random.rand(20), np.random.randint(0,10), np.random.random(1)))

/var/folders/lr/2zwst7m50b9gcy2vmd1l7bwm0000gn/T/ipykernel_31412/2631332426.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  rb.append(cpp.MDPTransition(np.random.rand(20), np.random.randint(0,10), np.random.random(1)))


In [21]:
rb.as_list()

In [22]:
jrb.as_list()[1]

NameError: name 'jrb' is not defined

In [30]:
rb.as_list()[0].get_action()


2